# Generated by Django 5.1 on 2024-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancebook',
            name='book_type',
            field=models.CharField(choices=[('1', 'Theory'), ('1', 'Practicle-1 Hr'), ('2', 'Practicle-2 Hr'), ('3', 'Practicle-3 Hr'), ('4', 'Practicle-4 Hr')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
