# Generated by Django 5.1 on 2024-08-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance_book', 'date', 'session')},
        ),
    ]
