# Generated by Django 5.1 on 2024-08-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancebook',
            name='book_type',
            field=models.CharField(choices=[('1', 'Theory'), ('1', 'Practicle-1 Hr'), ('2', 'Practicle-2 Hr'), ('3', 'Practicle-3 Hr'), ('4', 'Practicle-4 Hr')], default='1', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance_book', 'student', 'date', 'session')},
        ),
    ]
